### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by urbanmania** [Dagur/sarpur-xbmc#1]
You can search (although not with special Icelandic chars) but you can't play from the results.

Just wanted to check if you had any plans to fix or whether I should fork and have a go at fixing it :)

btw, love this addon

**Comment by Dagur** [comment]
Thanks for pointing this out, I didn't know about it. 

I will look at it as soon as possible but if you want to make a pull request then it would be appreciated :)

**Comment by urbanmania** [comment]
quick question for you on this as I'm just looking into it at the moment.  When you originally created the addon, did the search response include the URL to the playable media file or just to a HTML file on their server?  Currently the response doesn't include a link to the .mp4 file, so I'm just wondering what exactly changed on their end.

**Comment by Dagur** [comment]
I think it just returned the page url. When the user selects a search result the page should be scraped and the stream url found from there.

**Comment by sindrig** [comment]
Close this? 7f83988752d8500be04a715dd4c3bddaed7d7ddb fixed it.

*edit waiting for release 4.2.0 maybe?

**Comment by Dagur** [comment]
4.2.0 has been accepted by Kodi. Closing this issue
